'use client';
import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import WritingPad from '@/components/writing-pad';
import { ArrowRight, ArrowLeft, Volume2, PencilLine, BookOpen, SlidersHorizontal, Check, Download, Upload, RefreshCw, Headphones, Sparkles, Home, Delete, CloudCheck, CircleAlert } from 'lucide-react';
import { CHARACTERS, CONTENT_VERSION, DEFAULT_SETTINGS, character, spell, isPinyinCorrect, newId, validAttempt, validSession, validSettings, freshQuestion, createSession, mergeAttempts } from '@/lib/learning';
import { selectMandarinVoice, SPEECH_PROMPTS } from '@/lib/audio';
import type { Attempt, Settings, Session } from '@/lib/learning';
const DRAFT_KEY='little-hanzi-draft-v1', OUTBOX_KEY='little-hanzi-outbox-v1';
const USE_LOCAL_AUDIO=process.env.NEXT_PUBLIC_LOCAL_AUDIO==='1';
const LETTERS=['a','d','e','i','n','o','r','s','x','y','ü'];
const TONES=[['—','一声'],['／','二声'],['∨','三声'],['＼','四声'],['·','轻声']];
function localRead(key:string){try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}}
function localWrite(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
async function post(kind:string,value:unknown){const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,value})});if(!r.ok)throw new Error('Save failed');return r.json();}
export default function HomePage(){
  const [view,setView]=useState<'home'|'lesson'|'parent'>('home');
  const [session,setSession]=useState<Session|null>(null),[settings,setSettings]=useState<Settings>(DEFAULT_SETTINGS),[attempts,setAttempts]=useState<Attempt[]>([]);
  const [loaded,setLoaded]=useState(false),[status,setStatus]=useState('正在连接…'),[notice,setNotice]=useState(''),[audioBusy,setAudioBusy]=useState(false);
  const queue=useRef<Attempt[]>([]),syncing=useRef(false),audio=useRef<HTMLAudioElement|null>(null),speech=useRef<SpeechSynthesisUtterance|null>(null),latestSession=useRef(session),file=useRef<HTMLInputElement>(null);
  const failedDraft=useRef<Session|null>(null);
  useEffect(()=>{latestSession.current=session;},[session]);
  // oxlint-disable-next-line react/react-compiler -- Called only by input and drawing callbacks; timestamps are event data.
  function patch(updates:Partial<Session>){const s=latestSession.current;if(!s)return;const next={...s,...updates,updatedAt:Math.max(Date.now(),s.updatedAt+1)};latestSession.current=next;setSession(next);}
  function pauseSound(){const currentSpeech=speech.current;speech.current=null;if(currentSpeech&&typeof window!=='undefined'&&'speechSynthesis'in window)window.speechSynthesis.cancel();audio.current?.pause();audio.current=null;setAudioBusy(false);}
  async function play(name:string,onStart?:()=>void){pauseSound();setNotice('');if(USE_LOCAL_AUDIO){const a=new Audio(`/audio/${name}.m4a`);audio.current=a;let started=false;const began=()=>{if(audio.current!==a||started)return;started=true;setAudioBusy(true);onStart?.();};a.onplaying=began;a.onended=()=>{if(audio.current===a){audio.current=null;setAudioBusy(false);}};a.onerror=()=>{if(audio.current===a){audio.current=null;setAudioBusy(false);setNotice('声音还没准备好，请再点一次。');}};try{await a.play();}catch{if(audio.current===a){audio.current=null;setNotice('请点喇叭，再听一次。');setAudioBusy(false);}}return;}
    const text=SPEECH_PROMPTS[name],synth=typeof window!=='undefined'&&'speechSynthesis'in window?window.speechSynthesis:undefined;if(!text||!synth||typeof SpeechSynthesisUtterance==='undefined'){setNotice('这台设备暂时不能朗读，请检查浏览器的语音设置。');setAudioBusy(false);return;}
    const utterance=new SpeechSynthesisUtterance(text);utterance.lang='zh-CN';speech.current=utterance;utterance.onstart=()=>{if(speech.current===utterance){setAudioBusy(true);onStart?.();}};utterance.onend=()=>{if(speech.current===utterance){speech.current=null;setAudioBusy(false);}};utterance.onerror=()=>{if(speech.current===utterance){speech.current=null;setAudioBusy(false);setNotice('语音播放没有成功，请检查浏览器的中文语音设置，再试一次。');}};try{const voice=selectMandarinVoice(synth.getVoices());if(voice)utterance.voice=voice;synth.speak(utterance);}catch{if(speech.current===utterance){speech.current=null;setAudioBusy(false);setNotice('语音播放没有成功，请检查浏览器的中文语音设置，再试一次。');}}}
  async function sync(){if(syncing.current)return;syncing.current=true;try{while(queue.current.length||failedDraft.current){while(queue.current.length){const a=queue.current[0];setStatus('正在保存…');await post('attempt',a);queue.current=queue.current.filter(x=>x.id!==a.id);localWrite(OUTBOX_KEY,queue.current);}if(failedDraft.current){const d=failedDraft.current;await post('draft',d);if(failedDraft.current?.updatedAt===d.updatedAt)failedDraft.current=null;}}setStatus('已保存到 mini');}catch{setStatus('等待连接，稍后重试');}finally{syncing.current=false;}}
  function record(a:Attempt){setAttempts(old=>mergeAttempts(old,[a]));if(!queue.current.some(x=>x.id===a.id))queue.current.push(a);if(!localWrite(OUTBOX_KEY,queue.current))setNotice('这台设备暂时不能保存备份，请保持页面打开。');void sync();}
  async function load(){try{const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw new Error();const data=await r.json() as {attempts:unknown[];settings:unknown;draft:unknown};const saved=localRead(OUTBOX_KEY);queue.current=Array.isArray(saved)?saved.filter(validAttempt):[];setAttempts(mergeAttempts(data.attempts.filter(validAttempt),queue.current));if(validSettings(data.settings))setSettings(data.settings);const local=localRead(DRAFT_KEY),server=data.draft;const draft=validSession(local)&&(!validSession(server)||local.updatedAt>server.updatedAt)?local:server;if(validSession(draft))setSession(draft);setLoaded(true);setNotice('');setStatus('已保存到 mini');void sync();}catch{setStatus('还没连上 mini');setNotice('请确认和 mini 连在同一个 Wi-Fi，再点重试。');}}
  useEffect(()=>{void load();function resume(){if(document.visibilityState==='visible')void sync();else pauseSound();}document.addEventListener('visibilitychange',resume);window.addEventListener('online',sync);return()=>{document.removeEventListener('visibilitychange',resume);window.removeEventListener('online',sync);const currentSpeech=speech.current;speech.current=null;if(currentSpeech&&'speechSynthesis'in window)window.speechSynthesis.cancel();audio.current?.pause();audio.current=null;};},[]);
  useEffect(()=>{if(!loaded||!session)return;localWrite(DRAFT_KEY,session);failedDraft.current=session;const timer=setTimeout(()=>void sync(),250);return()=>clearTimeout(timer);},[session,loaded]);
  function start(mode:Session['mode']){pauseSound();setNotice('');setSession(createSession(settings,mode));setView('lesson');void play(mode==='lesson'?'welcome':'recognition');}
  function leave(next:'home'|'parent'){pauseSound();setNotice('');setView(next);void sync();}
  function makeAttempt(skill:Attempt['skill'],correct:boolean,answer:string,extra:Partial<Attempt>={}):Attempt{const s=latestSession.current!;return{id:`${s.id}:${s.index}:${skill}:${s.tries}`,at:new Date().toISOString(),characterId:s.ids[s.index],skill,mode:s.mode==='exam'?'exam':'practice',correct,assisted:false,mistakes:s.tries,first:s.tries===0,answer,responseMode:skill==='pinyin'?'spelling':'choice',contentVersion:CONTENT_VERSION,...extra};}
  function finishWriting(mistakes:number){const s=latestSession.current;if(!s||s.writingDone)return;record(makeAttempt('writing',true,'completed',{id:`${s.id}:${s.index}:writing`,assisted:!s.independent||s.writingHelp||mistakes>0,mistakes,first:mistakes===0,responseMode:s.independent?'independent-finger':'guided-finger'}));patch({writingDone:true,writingMistakes:mistakes});}
  function checkPinyin(){const s=latestSession.current;if(!s||s.checked||!s.raw||!s.tone)return;const ok=isPinyinCorrect(s.ids[s.index],s.raw,s.tone);record(makeAttempt('pinyin',ok,spell(s.raw,s.tone)));patch({checked:true,correct:ok,tries:s.tries+1});}
  function choose(id:string){const s=latestSession.current;if(!s||s.checked||!s.heard)return;const ok=id===s.ids[s.index];record(makeAttempt('recognition',ok,character(id).hanzi));patch({checked:true,correct:ok,choice:id,tries:s.tries+1});}
  function next(){const s=latestSession.current;if(!s)return;pauseSound();if(s.index+1===s.ids.length){patch({stage:'done'});return;}const index=s.index+1;patch({...freshQuestion(),index,stage:s.mode==='lesson'?'learn':index%2?'pinyin':'recognition'});}
  async function saveSettings(nextSettings:Settings){setNotice('');try{await post('settings',nextSettings);setSettings(nextSettings);setStatus('已保存到 mini');}catch{setNotice('设置没有保存成功，请再试一次。');}}
  function exportBackup(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),settings,attempts},null,2)],{type:'application/json'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=`little-hanzi-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(href),5000);}
  async function importBackup(f:File){try{if(f.size>400000)throw new Error();const data=JSON.parse(await f.text());if(data.version!==1)throw new Error();await post('import',data);await load();setNotice('已合并备份；已有记录会保留。');}catch{setNotice('无法导入这个备份，请选择本应用导出的 JSON 文件。');}if(file.current)file.current.value='';}
  const current=session?character(session.ids[session.index]):CHARACTERS[0];
  const runAttempts=session?attempts.filter(a=>a.id.startsWith(`${session.id}:`)):[];
  const examCorrect=runAttempts.filter(a=>a.correct&&a.first).length;
  const resumable=session&&session.stage!=='done';
  const cards=settings.enabled.slice(0,settings.lessonSize).map(character);
  return <main className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>leave('home')} aria-label="返回首页"><span className="brand-mark">字</span><span>小小汉字<small>一点一点，学会中文</small></span></button><Button variant="ghost" className="parent-button" onClick={()=>leave(view==='parent'?'home':'parent')}>{view==='parent'?<Home/>:<SlidersHorizontal/>}{view==='parent'?'回到学习':'家长'}</Button></header>
    {notice&&<output className="notice"><CircleAlert size={18}/><span>{notice}</span></output>}
    {!loaded?<section className="empty-state"><h2>准备好小课堂</h2><p>{status}</p><Button className="primary-action" onClick={()=>void load()}><RefreshCw/> 重试连接</Button></section>:<>
    {view==='home'&&<>
      <section className="welcome"><p className="eyebrow">今天的小发现 · 数字和我们</p><h1>小手写字，<br/><span>慢慢长本领。</span></h1><p>听一听，认一认，再用小手写一写。</p></section>
      <section className="lesson-card"><div><p className="eyebrow">一次 {cards.length} 个字 · 按自己的节奏</p><h2>今天，认识这些字</h2><div className="today-characters">{cards.map(c=><span key={c.id}>{c.hanzi}</span>)}</div><div className="tags"><span><Volume2/> 听发音</span><span><PencilLine/> 手指写字</span><span><BookOpen/> 拼音练习</span></div><Button className="primary-action" onClick={()=>resumable?(setView('lesson'),void play('welcome')):start('lesson')}>{resumable?'接着上次学':'开始今天的学习'} <ArrowRight/></Button>{resumable&&<p className="resume-note">已记住上次的位置 · {character(session.ids[session.index]).hanzi}</p>}</div><div className="character-preview"><span>{cards[0].hanzi}</span><small>{cards[0].pinyin}</small></div></section>
      <div className="home-bottom"><Button variant="outline" className="exam-entry" onClick={()=>start('exam')} disabled={!!resumable}><Sparkles/> 小小测验 <span>{Math.min(3,settings.enabled.length)} 题 · 不计时</span><ArrowRight/></Button><div className="home-note"><BookOpen/><p>每天一点点<br/><small>会读、会拼、会写，分别记录。</small></p></div></div>
      <p className="footer-note">{resumable?'完成上次的学习后，可以开始小测验。':'每次学一点，每次进步一点。'}</p>
    </>}
    {view==='lesson'&&session&&<>
      <div className="lesson-toolbar"><Button variant="ghost" className="back-button" onClick={()=>leave('home')}><ArrowLeft/> 暂停</Button><span>{session.mode==='lesson'?'今日学习':'小小测验'} · {session.stage==='done'?session.ids.length:session.index+1} / {session.ids.length}</span><Button variant="ghost" className="sound-button" onClick={()=>void play(session.stage==='write'?'write':session.stage==='recognition'?'recognition':session.stage==='pinyin'?'pinyin':'welcome')} aria-label="听说明"><Volume2/></Button></div>
      <Progress value={session.stage==='done'?100:((session.index+(session.stage==='learn'?0:session.stage==='write'?.35:.7))/session.ids.length)*100} aria-label="本次学习进度" className="lesson-progress"/>
      {session.stage==='learn'&&<section className="activity learn-activity"><p className="eyebrow">第一步 · 听一听，认一认</p><h2>和这个字打个招呼</h2><button className="big-character" style={{background:current.color}} onClick={()=>void play(current.id)} aria-label={`听${current.hanzi}的发音`}><span>{current.hanzi}</span><small>{current.pinyin} <Volume2/></small></button><Button variant="outline" className="word-button" onClick={()=>void play(`${current.id}-word`)}><Volume2/> {current.word}</Button><p className="gentle-caption">{current.meaning}</p><Button className="primary-action" onClick={()=>{patch({stage:'write'});void play('write');}}>用小手写一写 <ArrowRight/></Button></section>}
      {session.stage==='write'&&<section className="activity"><div className="activity-title"><div><p className="eyebrow">第二步 · 用手指写</p><h2>{session.independent?'听一听，自己写':'一笔一笔，慢慢来'}</h2></div><Button variant="outline" className="listen-button" onClick={()=>void play(current.id)}><Volume2/>{session.independent?'听这个字':current.hanzi}</Button></div><WritingPad key={`${session.id}-${session.index}`} item={current} independent={session.independent} stroke={session.writingStroke} mistakes={session.writingMistakes} done={session.writingDone} onProgress={(stroke,mistakes)=>patch({writingStroke:stroke,writingMistakes:mistakes})} onHelp={()=>patch({writingHelp:true})} onComplete={finishWriting} onMode={independent=>patch({independent,writingStroke:0,writingMistakes:0,writingHelp:false,writingDone:false})}/><Button className="primary-action wide-action" disabled={!session.writingDone} onClick={()=>{patch({stage:'pinyin'});void play('pinyin');}}>来拼一拼 <ArrowRight/></Button></section>}
      {session.stage==='pinyin'&&<section className="activity pinyin-activity"><p className="eyebrow">{session.mode==='exam'?'想一想，再作答':'第三步 · 字母和声调'}</p><h2>这个字的拼音怎么写？</h2><button className="pinyin-character" onClick={()=>void play(current.id)} aria-label="听这个字的发音">{current.hanzi}<Volume2/></button><div className="spelling-display" aria-live="polite">{spell(session.raw,session.tone)||<span>点字母，再选声调</span>}</div><div className="letter-keys">{LETTERS.map(k=><Button key={k} variant="outline" disabled={session.checked} onClick={()=>patch({raw:(session.raw+k).slice(0,10)})}>{k}</Button>)}<Button variant="outline" aria-label="删除一个字母" disabled={session.checked} onClick={()=>patch({raw:session.raw.slice(0,-1)})}><Delete/></Button></div><div className="tone-keys">{TONES.map(([mark,label],i)=><Button key={label} variant={session.tone===i+1?'secondary':'outline'} aria-pressed={session.tone===i+1} disabled={session.checked} onClick={()=>patch({tone:i+1})}><strong>{mark}</strong><small>{label}</small></Button>)}</div>
        <div className="answer-feedback" aria-live="polite">{session.checked?(session.mode==='exam'?<span>已记下你的答案，做完再一起看。</span>:session.correct?<span className="success-text"><Check/> 拼对了，真棒！</span>:<><span>再试一次：先听发音，再想想声调。</span><Button variant="ghost" onClick={()=>{patch({raw:'',tone:0,checked:false});void play(current.id);}}>听一听，再试试</Button></>):<span>拼音要有字母，也要有声调。</span>}</div>
        {!session.checked?<Button className="primary-action wide-action" disabled={!session.raw||!session.tone} onClick={checkPinyin}>我拼好了 <Check/></Button>:(session.correct||session.mode==='exam')?<Button className="primary-action wide-action" onClick={next}>{session.index+1===session.ids.length?'看看这次的收获':'下一个'} <ArrowRight/></Button>:<Button variant="outline" className="hint-answer" onClick={()=>{setNotice(`一起读：${current.hanzi}，${current.pinyin}。`);void play(current.id);record(makeAttempt('pinyin',false,'hint',{id:newId(),assisted:true,first:false,responseMode:'hint'}));}}>给我一点提示</Button>}
      </section>}
      {session.stage==='recognition'&&<section className="activity recognition-activity"><p className="eyebrow">听声音，找汉字</p><h2>你听到的是哪个字？</h2><Button className="listen-big" variant="secondary" onClick={()=>void play(current.id,()=>patch({heard:true}))}><Headphones/> {audioBusy?'正在听…':'点这里听一听'}</Button><div className="choice-grid">{CHARACTERS.map(c=><Button key={c.id} variant="outline" className={session.choice===c.id?'selected-choice':''} disabled={!session.heard||session.checked} onClick={()=>choose(c.id)}>{c.hanzi}</Button>)}</div><p className="gentle-caption" aria-live="polite">{session.checked?'已记下你的答案，做完再一起看。':'先听一听，再点一个字。'}</p><Button className="primary-action wide-action" disabled={!session.checked} onClick={next}>{session.index+1===session.ids.length?'看看这次的收获':'下一题'} <ArrowRight/></Button></section>}
      {session.stage==='done'&&<section className="activity done-activity"><div className="done-seal"><Check/></div><p className="eyebrow">小小的练习，大大的进步</p><h2>{session.mode==='exam'?'这次测验完成啦！':'今天又多认识了几个字！'}</h2><div className="done-characters">{session.ids.map(id=><span key={id}>{character(id).hanzi}</span>)}</div><p>{session.mode==='exam'?`独立答对 ${examCorrect} / ${session.ids.length} 题。一起看看还有什么可以练习。`:'听过、写过、拼过。明天再见，也试试能不能记住。'}</p>{session.mode==='exam'&&<div className="exam-results">{runAttempts.map(a=><div key={a.id}><span>{character(a.characterId).hanzi} · {a.skill==='pinyin'?'拼音':'认字'}</span><span>{a.correct?'答对了':`这次答案：${a.answer} · 再练练`}</span><strong>{a.skill==='pinyin'?character(a.characterId).pinyin:character(a.characterId).hanzi}</strong></div>)}</div>}<Button className="primary-action" onClick={()=>leave('home')}>回到小课堂 <Home/></Button><Button variant="ghost" className="parent-results" onClick={()=>leave('parent')}>和家长一起看记录 <ArrowRight/></Button></section>}
    </>}
    {view==='parent'&&<section className="parent-view"><p className="eyebrow">家长的小本子</p><h1>按孩子的节奏来。</h1><p className="parent-intro">选择这次教什么，看看哪些任务能独立完成。</p><div className="parent-panel"><h2>安排下一次学习</h2><p>点选要学的字。正在进行的学习会保留原来的安排。</p><div className="curriculum">{CHARACTERS.map(c=><Button key={c.id} variant={settings.enabled.includes(c.id)?'secondary':'outline'} aria-pressed={settings.enabled.includes(c.id)} onClick={()=>{const enabled=settings.enabled.includes(c.id)?settings.enabled.filter(id=>id!==c.id):CHARACTERS.filter(x=>settings.enabled.includes(x.id)||x.id===c.id).map(x=>x.id);if(enabled.length)void saveSettings({...settings,enabled});}}>{c.hanzi}<small>{c.pinyin}</small>{settings.enabled.includes(c.id)&&<Check/>}</Button>)}</div><div className="pace-row"><span>一次学几个字</span>{[1,2,3].map(n=><Button key={n} variant={settings.lessonSize===n?'secondary':'outline'} aria-pressed={settings.lessonSize===n} onClick={()=>void saveSettings({...settings,lessonSize:n})}>{n} 个</Button>)}</div></div><div className="parent-panel"><h2>分开看每种本领</h2><p>这里记录的是实际练习，不把跟写当成独立书写。</p><div className="table-wrap"><table><thead><tr><th>汉字</th><th>认字 · 独立首答</th><th>拼音 · 独立首答</th><th>手指写字</th></tr></thead><tbody>{CHARACTERS.map(c=>{const records=attempts.filter(a=>a.characterId===c.id);const reads=records.filter(a=>a.skill==='recognition'&&a.first&&!a.assisted),py=records.filter(a=>a.skill==='pinyin'&&a.first&&!a.assisted),wr=records.filter(a=>a.skill==='writing');return<tr key={c.id}><th>{c.hanzi}<small>{c.pinyin}</small></th><td>{reads.length?`${reads.filter(a=>a.correct).length} / ${reads.length} 答对`:'还没测过'}</td><td>{py.length?`${py.filter(a=>a.correct).length} / ${py.length} 答对`:'还没测过'}</td><td>{wr.length?<>{wr.filter(a=>!a.assisted).length} 次独立完成<small>{wr.filter(a=>a.assisted).length} 次跟写 / 有帮助</small></>:'还没练过'}</td></tr>;})}</tbody></table></div><p className="small-note">手指练习通过，表示完成了当前笔画任务。纸笔书写可以另外和孩子试一试。</p></div><div className="parent-panel backup-panel"><div><h2>保留学习记录</h2><p>{attempts.length} 条练习记录 · 一个家庭共用一个学习档案</p><p className="small-note">记录保存在 mini。导出一份备份，可以日后重新导入。</p></div><div className="backup-actions"><Button variant="outline" onClick={exportBackup}><Download/> 导出记录</Button><Button variant="outline" onClick={()=>file.current?.click()}><Upload/> 导入备份</Button><input hidden ref={file} type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importBackup(f);}}/></div></div><a className="credits-link" href="/credits" target="_blank" rel="noreferrer">笔画资料与使用说明</a></section>}
    <footer className="save-status"><span className={status.startsWith('已')?'saved':'pending'}>{status.startsWith('已')?<CloudCheck size={16}/>:<RefreshCw size={16}/>} {status}</span>{!status.startsWith('已')&&<Button variant="ghost" onClick={()=>void sync()}>重试保存</Button>}</footer>
    </>}
  </main>;
}
