/** Frozen pure schema constants; derived from approved SQL without execution. */
export const OPS_MIGRATION_SHA =
  '26aa0f39b7b8cc7c06e8351f4d1b98d42f35425553db216cbfe5859cd49d429a';
export const OPS_DOMAIN_TABLES = [
  'ops_job',
  'ops_job_event',
  'ops_archive',
  'ops_alert_event',
  'ops_feedback',
  'ops_feedback_event',
] as const;
export const OPS_TABLES = [
  'ops_job',
  'ops_job_event',
  'ops_archive',
  'ops_alert_event',
  'ops_feedback',
  'ops_feedback_event',
  'ops_installation',
  'ops_schema_history',
] as const;
export const OPS_COLUMNS = {
  ops_schema_history: ['version', 'name', 'checksum', 'applied_at'],
  ops_installation: [
    'id',
    'installation_id',
    'environment',
    'learning_installation_id',
    'schema_version',
    'queue_revision',
    'created_at',
  ],
  ops_job: [
    'id',
    'environment',
    'installation_id',
    'ops_installation_id',
    'build_id',
    'kind',
    'utc_slot',
    'objects_json',
    'revision',
    'status',
    'attempt_id',
    'attempt_number',
    'lease_until',
    'started_at',
    'ended_at',
    'error_code',
    'latest_event_id',
  ],
  ops_job_event: [
    'id',
    'job_id',
    'environment',
    'installation_id',
    'ops_installation_id',
    'sequence',
    'previous_event_id',
    'attempt_id',
    'kind',
    'status_after',
    'request_digest',
    'public_json',
    'created_at',
  ],
  ops_archive: [
    'id',
    'job_id',
    'attempt_id',
    'environment',
    'installation_id',
    'ops_installation_id',
    'build_id',
    'kind',
    'format',
    'object_ref',
    'key_id',
    'plaintext_digest',
    'ciphertext_digest',
    'byte_size',
    'data_at',
    'created_at',
    'verified_at',
    'daily_slot',
    'weekly_slot',
    'verification_event_id',
  ],
  ops_alert_event: [
    'id',
    'alert_id',
    'environment',
    'installation_id',
    'ops_installation_id',
    'build_id',
    'sequence',
    'previous_event_id',
    'kind',
    'status_after',
    'code',
    'job_id',
    'actor_user_id',
    'request_id',
    'actor_key',
    'request_digest',
    'receipt_json',
    'public_json',
    'created_at',
  ],
  ops_feedback: [
    'id',
    'environment',
    'installation_id',
    'ops_installation_id',
    'build_id',
    'kind',
    'submission_build_id',
    'source_role',
    'actor_key',
    'operator_user_id',
    'request_id',
    'request_digest',
    'request_json',
    'receipt_json',
    'child_id',
    'run_id',
    'run_installation_id',
    'candidate_id',
    'lesson_id',
    'lesson_version',
    'content_digest',
    'category',
    'observation_kind',
    'observed_at',
    'private_json',
    'created_at',
    'expires_at',
    'revision',
    'severity',
    'owner_ref',
    'status',
    'next_review_at',
    'updated_at',
    'details_removed_at',
    'latest_event_id',
    'redaction_event_id',
  ],
  ops_feedback_event: [
    'id',
    'record_id',
    'environment',
    'installation_id',
    'ops_installation_id',
    'sequence',
    'previous_event_id',
    'kind',
    'actor_user_id',
    'actor_key',
    'request_id',
    'request_digest',
    'request_json',
    'receipt_json',
    'public_json',
    'private_json',
    'redacted_at',
    'created_at',
  ],
} as const;
export const OPS_SCHEMA = [
  {
    type: 'table',
    name: 'ops_schema_history',
    tbl_name: 'ops_schema_history',
    sql: "CREATE TABLE ops_schema_history (\n  version INTEGER PRIMARY KEY CHECK (version = 0),\n  name TEXT NOT NULL CHECK (name = '0000_ops.sql'),\n  checksum TEXT NOT NULL CHECK (length(checksum) = 64),\n  applied_at INTEGER NOT NULL CHECK (applied_at >= 0)\n)",
  },
  {
    type: 'table',
    name: 'ops_installation',
    tbl_name: 'ops_installation',
    sql: "CREATE TABLE ops_installation (\n  id INTEGER PRIMARY KEY CHECK (id = 1),\n  installation_id TEXT NOT NULL UNIQUE,\n  environment TEXT NOT NULL,\n  learning_installation_id TEXT NOT NULL,\n  schema_version TEXT NOT NULL CHECK (schema_version = 'pilot-ops-schema-1'),\n  queue_revision INTEGER NOT NULL DEFAULT 0 CHECK (queue_revision >= 0),\n  created_at INTEGER NOT NULL CHECK (created_at >= 0)\n)",
  },
  {
    type: 'table',
    name: 'ops_job',
    tbl_name: 'ops_job',
    sql: "CREATE TABLE ops_job (\n  id TEXT PRIMARY KEY,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  build_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK (kind IN ('backup','monitor','retention','reconcile')),\n  utc_slot TEXT NOT NULL,\n  objects_json TEXT NOT NULL CHECK (json_valid(objects_json)),\n  revision INTEGER NOT NULL CHECK (revision >= 1),\n  status TEXT NOT NULL CHECK (status IN ('running','uncertain','succeeded','failed')),\n  attempt_id TEXT NOT NULL,\n  attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),\n  lease_until INTEGER,\n  started_at INTEGER NOT NULL CHECK (started_at >= 0),\n  ended_at INTEGER,\n  error_code TEXT,\n  latest_event_id TEXT NOT NULL,\n  UNIQUE (environment,installation_id,ops_installation_id,kind,utc_slot),\n  UNIQUE (id,environment,installation_id,ops_installation_id),\n  CHECK (lease_until IS NULL OR lease_until >= started_at),\n  CHECK (ended_at IS NULL OR ended_at >= started_at),\n  CHECK ((status = 'running' AND lease_until IS NOT NULL AND ended_at IS NULL)\n    OR (status = 'uncertain' AND lease_until IS NULL AND ended_at IS NULL)\n    OR (status IN ('succeeded','failed') AND lease_until IS NULL AND ended_at IS NOT NULL)),\n  FOREIGN KEY (latest_event_id,id,revision,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job_event(id,job_id,sequence,environment,installation_id,ops_installation_id)\n    DEFERRABLE INITIALLY DEFERRED\n)",
  },
  {
    type: 'table',
    name: 'ops_job_event',
    tbl_name: 'ops_job_event',
    sql: "CREATE TABLE ops_job_event (\n  id TEXT PRIMARY KEY,\n  job_id TEXT NOT NULL,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  sequence INTEGER NOT NULL CHECK (sequence >= 1),\n  previous_event_id TEXT,\n  attempt_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK (kind IN ('acquired','uncertain','archive-verified','completed','failed','reconciled','archive-deleted')),\n  status_after TEXT NOT NULL CHECK (status_after IN ('running','uncertain','succeeded','failed')),\n  request_digest TEXT NOT NULL CHECK (length(request_digest) = 71 AND substr(request_digest,1,7) = 'sha256:'),\n  public_json TEXT NOT NULL CHECK (json_valid(public_json)),\n  created_at INTEGER NOT NULL CHECK (created_at >= 0),\n  UNIQUE (job_id,sequence),\n  UNIQUE (id,job_id,sequence,environment,installation_id,ops_installation_id),\n  UNIQUE (id,job_id,environment,installation_id,ops_installation_id),\n  CHECK ((sequence = 1 AND previous_event_id IS NULL) OR (sequence > 1 AND previous_event_id IS NOT NULL)),\n  FOREIGN KEY (job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job(id,environment,installation_id,ops_installation_id),\n  FOREIGN KEY (previous_event_id,job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job_event(id,job_id,environment,installation_id,ops_installation_id)\n)",
  },
  {
    type: 'table',
    name: 'ops_archive',
    tbl_name: 'ops_archive',
    sql: "CREATE TABLE ops_archive (\n  id TEXT PRIMARY KEY,\n  job_id TEXT NOT NULL,\n  attempt_id TEXT NOT NULL,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  build_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK (kind IN ('learning','operations')),\n  format TEXT NOT NULL CHECK (format IN ('pilot-admin-backup-4','pilot-ops-backup-1')),\n  object_ref TEXT NOT NULL,\n  key_id TEXT NOT NULL,\n  plaintext_digest TEXT NOT NULL CHECK (length(plaintext_digest) = 71 AND substr(plaintext_digest,1,7) = 'sha256:'),\n  ciphertext_digest TEXT NOT NULL CHECK (length(ciphertext_digest) = 71 AND substr(ciphertext_digest,1,7) = 'sha256:'),\n  byte_size INTEGER NOT NULL CHECK (byte_size > 0),\n  data_at INTEGER NOT NULL CHECK (data_at >= 0),\n  created_at INTEGER NOT NULL CHECK (created_at >= data_at),\n  verified_at INTEGER NOT NULL CHECK (verified_at >= created_at),\n  daily_slot TEXT NOT NULL,\n  weekly_slot TEXT,\n  verification_event_id TEXT NOT NULL,\n  UNIQUE (job_id,attempt_id,kind),\n  UNIQUE (environment,ops_installation_id,object_ref),\n  UNIQUE (id,environment,installation_id,ops_installation_id),\n  CHECK ((kind = 'learning' AND format = 'pilot-admin-backup-4') OR (kind = 'operations' AND format = 'pilot-ops-backup-1')),\n  FOREIGN KEY (job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job(id,environment,installation_id,ops_installation_id),\n  FOREIGN KEY (verification_event_id,job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job_event(id,job_id,environment,installation_id,ops_installation_id)\n    DEFERRABLE INITIALLY DEFERRED\n)",
  },
  {
    type: 'table',
    name: 'ops_alert_event',
    tbl_name: 'ops_alert_event',
    sql: "CREATE TABLE ops_alert_event (\n  id TEXT PRIMARY KEY,\n  alert_id TEXT NOT NULL,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  build_id TEXT NOT NULL,\n  sequence INTEGER NOT NULL CHECK (sequence >= 1),\n  previous_event_id TEXT,\n  kind TEXT NOT NULL CHECK (kind IN ('opened','reopened','acknowledged','resolved','notification-delivered','notification-failed')),\n  status_after TEXT NOT NULL CHECK (status_after IN ('open','acknowledged','resolved')),\n  code TEXT NOT NULL CHECK (code IN ('OPS_BACKUP_FAILED','OPS_PROBE_FAILED','OPS_BACKUP_STALE','OPS_MONITOR_UNKNOWN','OPS_NOTIFICATION_FAILED','OPS_RETENTION_FAILED')),\n  job_id TEXT,\n  actor_user_id TEXT,\n  request_id TEXT NOT NULL,\n  actor_key TEXT NOT NULL,\n  request_digest TEXT NOT NULL CHECK (length(request_digest) = 71 AND substr(request_digest,1,7) = 'sha256:'),\n  receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json)),\n  public_json TEXT NOT NULL CHECK (json_valid(public_json)),\n  created_at INTEGER NOT NULL CHECK (created_at >= 0),\n  UNIQUE (alert_id,sequence),\n  UNIQUE (environment,installation_id,ops_installation_id,actor_key,request_id),\n  UNIQUE (id,alert_id,environment,installation_id,ops_installation_id),\n  CHECK ((sequence = 1 AND previous_event_id IS NULL) OR (sequence > 1 AND previous_event_id IS NOT NULL)),\n  CHECK ((sequence = 1 AND kind = 'opened') OR (sequence > 1 AND kind <> 'opened')),\n  FOREIGN KEY (job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job(id,environment,installation_id,ops_installation_id),\n  FOREIGN KEY (previous_event_id,alert_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_alert_event(id,alert_id,environment,installation_id,ops_installation_id)\n)",
  },
  {
    type: 'table',
    name: 'ops_feedback',
    tbl_name: 'ops_feedback',
    sql: "CREATE TABLE ops_feedback (\n  id TEXT PRIMARY KEY,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  build_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK (kind IN ('feedback','observation')),\n  submission_build_id TEXT NOT NULL,\n  source_role TEXT NOT NULL CHECK (source_role IN ('parent','operator')),\n  actor_key TEXT NOT NULL,\n  operator_user_id TEXT,\n  request_id TEXT NOT NULL,\n  request_digest TEXT NOT NULL CHECK (length(request_digest) = 71 AND substr(request_digest,1,7) = 'sha256:'),\n  request_json TEXT CHECK (request_json IS NULL OR json_valid(request_json)),\n  receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json)),\n  child_id TEXT,\n  run_id TEXT,\n  run_installation_id TEXT,\n  candidate_id TEXT NOT NULL,\n  lesson_id TEXT NOT NULL,\n  lesson_version TEXT NOT NULL,\n  content_digest TEXT NOT NULL CHECK (length(content_digest) = 71 AND substr(content_digest,1,7) = 'sha256:'),\n  category TEXT CHECK (category IN ('confusion','sound','saving','access','other')),\n  observation_kind TEXT CHECK (observation_kind IN ('actual','synthetic')),\n  observed_at INTEGER CHECK (observed_at IS NULL OR observed_at >= 0),\n  private_json TEXT CHECK (private_json IS NULL OR json_valid(private_json)),\n  created_at INTEGER NOT NULL CHECK (created_at >= 0),\n  expires_at INTEGER NOT NULL CHECK (expires_at = created_at + 2592000000),\n  revision INTEGER NOT NULL CHECK (revision >= 1),\n  severity TEXT NOT NULL CHECK (severity IN ('blocking','high','normal','low')),\n  owner_ref TEXT,\n  status TEXT NOT NULL CHECK (status IN ('open','in-progress','awaiting-review','resolved','expired')),\n  next_review_at INTEGER CHECK (next_review_at IS NULL OR next_review_at >= 0),\n  updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),\n  details_removed_at INTEGER,\n  latest_event_id TEXT NOT NULL,\n  redaction_event_id TEXT,\n  UNIQUE (environment,installation_id,ops_installation_id,actor_key,request_id),\n  UNIQUE (id,environment,installation_id,ops_installation_id),\n  CHECK ((kind = 'feedback' AND source_role = 'parent' AND child_id IS NOT NULL AND run_id IS NOT NULL AND run_installation_id IS NOT NULL AND category IS NOT NULL AND observation_kind IS NULL AND observed_at IS NULL AND operator_user_id IS NULL)\n    OR (kind = 'observation' AND source_role = 'operator' AND child_id IS NULL AND run_id IS NULL AND run_installation_id IS NULL AND category IS NULL AND observation_kind IS NOT NULL AND observed_at IS NOT NULL AND operator_user_id IS NOT NULL)),\n  CHECK ((details_removed_at IS NULL AND status <> 'expired' AND private_json IS NOT NULL AND request_json IS NOT NULL AND redaction_event_id IS NULL)\n    OR (details_removed_at IS NOT NULL AND details_removed_at >= expires_at AND status = 'expired' AND private_json IS NULL AND request_json IS NULL AND owner_ref IS NULL AND next_review_at IS NULL AND redaction_event_id IS NOT NULL AND redaction_event_id = latest_event_id)),\n  FOREIGN KEY (latest_event_id,id,revision,environment,installation_id,ops_installation_id)\n    REFERENCES ops_feedback_event(id,record_id,sequence,environment,installation_id,ops_installation_id)\n    DEFERRABLE INITIALLY DEFERRED\n)",
  },
  {
    type: 'table',
    name: 'ops_feedback_event',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TABLE ops_feedback_event (\n  id TEXT PRIMARY KEY,\n  record_id TEXT NOT NULL,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  sequence INTEGER NOT NULL CHECK (sequence >= 1),\n  previous_event_id TEXT,\n  kind TEXT NOT NULL CHECK (kind IN ('submitted','triaged','corrected','redacted')),\n  actor_user_id TEXT,\n  actor_key TEXT NOT NULL,\n  request_id TEXT NOT NULL,\n  request_digest TEXT NOT NULL CHECK (length(request_digest) = 71 AND substr(request_digest,1,7) = 'sha256:'),\n  request_json TEXT CHECK (request_json IS NULL OR json_valid(request_json)),\n  receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json)),\n  public_json TEXT NOT NULL CHECK (json_valid(public_json)),\n  private_json TEXT CHECK (private_json IS NULL OR json_valid(private_json)),\n  redacted_at INTEGER,\n  created_at INTEGER NOT NULL CHECK (created_at >= 0),\n  UNIQUE (record_id,sequence),\n  UNIQUE (environment,installation_id,ops_installation_id,actor_key,request_id),\n  UNIQUE (id,record_id,sequence,environment,installation_id,ops_installation_id),\n  UNIQUE (id,record_id,environment,installation_id,ops_installation_id),\n  CHECK ((sequence = 1 AND previous_event_id IS NULL AND kind = 'submitted') OR (sequence > 1 AND previous_event_id IS NOT NULL AND kind <> 'submitted')),\n  CHECK ((redacted_at IS NULL AND kind <> 'redacted' AND request_json IS NOT NULL AND private_json IS NOT NULL)\n    OR (redacted_at IS NOT NULL AND request_json IS NULL AND private_json IS NULL)),\n  FOREIGN KEY (record_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_feedback(id,environment,installation_id,ops_installation_id),\n  FOREIGN KEY (previous_event_id,record_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_feedback_event(id,record_id,environment,installation_id,ops_installation_id)\n)",
  },
  {
    type: 'index',
    name: 'ops_job_current',
    tbl_name: 'ops_job',
    sql: 'CREATE INDEX ops_job_current ON ops_job(environment,installation_id,ops_installation_id,status,started_at,id)',
  },
  {
    type: 'index',
    name: 'ops_archive_points',
    tbl_name: 'ops_archive',
    sql: 'CREATE INDEX ops_archive_points ON ops_archive(environment,installation_id,ops_installation_id,kind,verified_at,id)',
  },
  {
    type: 'index',
    name: 'ops_alert_latest',
    tbl_name: 'ops_alert_event',
    sql: 'CREATE INDEX ops_alert_latest ON ops_alert_event(environment,installation_id,ops_installation_id,alert_id,sequence DESC)',
  },
  {
    type: 'index',
    name: 'ops_alert_condition',
    tbl_name: 'ops_alert_event',
    sql: "CREATE UNIQUE INDEX ops_alert_condition ON ops_alert_event(environment,installation_id,ops_installation_id,code) WHERE kind='opened'",
  },
  {
    type: 'index',
    name: 'ops_feedback_queue',
    tbl_name: 'ops_feedback',
    sql: 'CREATE INDEX ops_feedback_queue ON ops_feedback(environment,installation_id,ops_installation_id,status,kind,created_at,id)',
  },
  {
    type: 'index',
    name: 'ops_feedback_expiry',
    tbl_name: 'ops_feedback',
    sql: 'CREATE INDEX ops_feedback_expiry ON ops_feedback(details_removed_at,expires_at,id)',
  },
  {
    type: 'trigger',
    name: 'ops_job_event_chain',
    tbl_name: 'ops_job_event',
    sql: "CREATE TRIGGER ops_job_event_chain BEFORE INSERT ON ops_job_event WHEN NEW.sequence > 1 BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM ops_job_event WHERE id=NEW.previous_event_id AND job_id=NEW.job_id AND sequence=NEW.sequence-1 AND created_at<=NEW.created_at)\n    THEN RAISE(ABORT,'OPS_EVENT_CHAIN') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_alert_event_chain',
    tbl_name: 'ops_alert_event',
    sql: "CREATE TRIGGER ops_alert_event_chain BEFORE INSERT ON ops_alert_event WHEN NEW.sequence > 1 BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM ops_alert_event WHERE id=NEW.previous_event_id AND alert_id=NEW.alert_id AND code=NEW.code AND sequence=NEW.sequence-1 AND created_at<=NEW.created_at)\n    THEN RAISE(ABORT,'OPS_EVENT_CHAIN') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_event_chain',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_event_chain BEFORE INSERT ON ops_feedback_event WHEN NEW.sequence > 1 BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM ops_feedback_event WHERE id=NEW.previous_event_id AND record_id=NEW.record_id AND sequence=NEW.sequence-1 AND created_at<=NEW.created_at)\n    THEN RAISE(ABORT,'OPS_EVENT_CHAIN') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_redaction_insert',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_redaction_insert BEFORE INSERT ON ops_feedback_event WHEN NEW.kind='redacted' BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM ops_feedback WHERE id=NEW.record_id AND status='expired' AND details_removed_at=NEW.redacted_at AND latest_event_id=NEW.id AND expires_at<=NEW.created_at)\n    THEN RAISE(ABORT,'OPS_REDACTION_INVALID') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_expired_final_event',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_expired_final_event BEFORE INSERT ON ops_feedback_event WHEN NEW.kind<>'redacted' BEGIN\n  SELECT CASE WHEN EXISTS (SELECT 1 FROM ops_feedback WHERE id=NEW.record_id AND status='expired' AND revision=NEW.sequence)\n    THEN RAISE(ABORT,'OPS_REDACTION_INVALID') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_expired_projection',
    tbl_name: 'ops_feedback',
    sql: "CREATE TRIGGER ops_feedback_expired_projection BEFORE UPDATE ON ops_feedback WHEN NEW.status='expired' BEGIN\n  SELECT CASE WHEN EXISTS (SELECT 1 FROM ops_feedback_event WHERE id=NEW.latest_event_id AND kind<>'redacted')\n    THEN RAISE(ABORT,'OPS_REDACTION_INVALID') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_queue_insert',
    tbl_name: 'ops_feedback',
    sql: 'CREATE TRIGGER ops_feedback_queue_insert AFTER INSERT ON ops_feedback BEGIN\n  UPDATE ops_installation SET queue_revision=queue_revision+1 WHERE id=1;\nEND',
  },
  {
    type: 'trigger',
    name: 'ops_feedback_queue_update',
    tbl_name: 'ops_feedback',
    sql: 'CREATE TRIGGER ops_feedback_queue_update AFTER UPDATE ON ops_feedback BEGIN\n  UPDATE ops_installation SET queue_revision=queue_revision+1 WHERE id=1;\nEND',
  },
  {
    type: 'trigger',
    name: 'ops_schema_history_no_update',
    tbl_name: 'ops_schema_history',
    sql: "CREATE TRIGGER ops_schema_history_no_update BEFORE UPDATE ON ops_schema_history BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_schema_history_no_delete',
    tbl_name: 'ops_schema_history',
    sql: "CREATE TRIGGER ops_schema_history_no_delete BEFORE DELETE ON ops_schema_history BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_installation_no_delete',
    tbl_name: 'ops_installation',
    sql: "CREATE TRIGGER ops_installation_no_delete BEFORE DELETE ON ops_installation BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_installation_identity',
    tbl_name: 'ops_installation',
    sql: "CREATE TRIGGER ops_installation_identity BEFORE UPDATE ON ops_installation WHEN NEW.installation_id IS NOT OLD.installation_id OR NEW.environment IS NOT OLD.environment OR NEW.learning_installation_id IS NOT OLD.learning_installation_id OR NEW.schema_version IS NOT OLD.schema_version OR NEW.created_at IS NOT OLD.created_at OR NEW.queue_revision<OLD.queue_revision BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_job_no_delete',
    tbl_name: 'ops_job',
    sql: "CREATE TRIGGER ops_job_no_delete BEFORE DELETE ON ops_job BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_job_identity',
    tbl_name: 'ops_job',
    sql: "CREATE TRIGGER ops_job_identity BEFORE UPDATE ON ops_job WHEN NEW.id IS NOT OLD.id OR NEW.environment IS NOT OLD.environment OR NEW.installation_id IS NOT OLD.installation_id OR NEW.ops_installation_id IS NOT OLD.ops_installation_id OR NEW.build_id IS NOT OLD.build_id OR NEW.kind IS NOT OLD.kind OR NEW.utc_slot IS NOT OLD.utc_slot OR NEW.objects_json IS NOT OLD.objects_json OR NEW.revision<>OLD.revision+1 BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_job_event_no_update',
    tbl_name: 'ops_job_event',
    sql: "CREATE TRIGGER ops_job_event_no_update BEFORE UPDATE ON ops_job_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_job_event_no_delete',
    tbl_name: 'ops_job_event',
    sql: "CREATE TRIGGER ops_job_event_no_delete BEFORE DELETE ON ops_job_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_archive_no_update',
    tbl_name: 'ops_archive',
    sql: "CREATE TRIGGER ops_archive_no_update BEFORE UPDATE ON ops_archive BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_archive_no_delete',
    tbl_name: 'ops_archive',
    sql: "CREATE TRIGGER ops_archive_no_delete BEFORE DELETE ON ops_archive BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_alert_event_no_update',
    tbl_name: 'ops_alert_event',
    sql: "CREATE TRIGGER ops_alert_event_no_update BEFORE UPDATE ON ops_alert_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_alert_event_no_delete',
    tbl_name: 'ops_alert_event',
    sql: "CREATE TRIGGER ops_alert_event_no_delete BEFORE DELETE ON ops_alert_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_no_delete',
    tbl_name: 'ops_feedback',
    sql: "CREATE TRIGGER ops_feedback_no_delete BEFORE DELETE ON ops_feedback BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_identity',
    tbl_name: 'ops_feedback',
    sql: "CREATE TRIGGER ops_feedback_identity BEFORE UPDATE ON ops_feedback WHEN NEW.id IS NOT OLD.id OR NEW.environment IS NOT OLD.environment OR NEW.installation_id IS NOT OLD.installation_id OR NEW.ops_installation_id IS NOT OLD.ops_installation_id OR NEW.build_id IS NOT OLD.build_id OR NEW.kind IS NOT OLD.kind OR NEW.submission_build_id IS NOT OLD.submission_build_id OR NEW.source_role IS NOT OLD.source_role OR NEW.actor_key IS NOT OLD.actor_key OR NEW.operator_user_id IS NOT OLD.operator_user_id OR NEW.request_id IS NOT OLD.request_id OR NEW.request_digest IS NOT OLD.request_digest OR NEW.receipt_json IS NOT OLD.receipt_json OR NEW.child_id IS NOT OLD.child_id OR NEW.run_id IS NOT OLD.run_id OR NEW.run_installation_id IS NOT OLD.run_installation_id OR NEW.candidate_id IS NOT OLD.candidate_id OR NEW.lesson_id IS NOT OLD.lesson_id OR NEW.lesson_version IS NOT OLD.lesson_version OR NEW.content_digest IS NOT OLD.content_digest OR NEW.category IS NOT OLD.category OR NEW.observation_kind IS NOT OLD.observation_kind OR NEW.observed_at IS NOT OLD.observed_at OR NEW.created_at IS NOT OLD.created_at OR NEW.expires_at IS NOT OLD.expires_at OR NEW.revision<>OLD.revision+1 OR OLD.details_removed_at IS NOT NULL OR NEW.updated_at<OLD.updated_at BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_private_update',
    tbl_name: 'ops_feedback',
    sql: "CREATE TRIGGER ops_feedback_private_update BEFORE UPDATE ON ops_feedback WHEN (NEW.request_json IS NOT OLD.request_json OR NEW.private_json IS NOT OLD.private_json) AND NOT (NEW.request_json IS NULL AND NEW.private_json IS NULL AND OLD.details_removed_at IS NULL AND NEW.details_removed_at>=OLD.expires_at AND NEW.status='expired') BEGIN SELECT RAISE(ABORT,'OPS_REDACTION_INVALID'); END",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_event_no_delete',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_event_no_delete BEFORE DELETE ON ops_feedback_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_event_redaction',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_event_redaction BEFORE UPDATE ON ops_feedback_event BEGIN\n  SELECT CASE WHEN NEW.id IS NOT OLD.id OR NEW.record_id IS NOT OLD.record_id OR NEW.environment IS NOT OLD.environment OR NEW.installation_id IS NOT OLD.installation_id OR NEW.ops_installation_id IS NOT OLD.ops_installation_id OR NEW.sequence IS NOT OLD.sequence OR NEW.previous_event_id IS NOT OLD.previous_event_id OR NEW.kind IS NOT OLD.kind OR NEW.actor_user_id IS NOT OLD.actor_user_id OR NEW.actor_key IS NOT OLD.actor_key OR NEW.request_id IS NOT OLD.request_id OR NEW.request_digest IS NOT OLD.request_digest OR NEW.receipt_json IS NOT OLD.receipt_json OR NEW.public_json IS NOT OLD.public_json OR NEW.created_at IS NOT OLD.created_at OR OLD.redacted_at IS NOT NULL OR NEW.request_json IS NOT NULL OR NEW.private_json IS NOT NULL OR NEW.redacted_at IS NULL OR NOT EXISTS (SELECT 1 FROM ops_feedback WHERE id=NEW.record_id AND details_removed_at=NEW.redacted_at AND details_removed_at>=expires_at AND status='expired')\n    THEN RAISE(ABORT,'OPS_REDACTION_INVALID') END;\nEND",
  },
] as const;

export const OPS_MIGRATION_V2_SHA =
  '9bbb359d9a28ac0942976980a60bf26742e4df7e2bf837f49712b73d1b7686cf';
export const OPS_SCHEMA_V2 = [
  {
    type: 'index',
    name: 'ops_alert_condition',
    tbl_name: 'ops_alert_event',
    sql: "CREATE UNIQUE INDEX ops_alert_condition ON ops_alert_event(environment,installation_id,ops_installation_id,code) WHERE kind='opened'",
  },
  {
    type: 'table',
    name: 'ops_alert_event',
    tbl_name: 'ops_alert_event',
    sql: "CREATE TABLE ops_alert_event (\n  id TEXT PRIMARY KEY,\n  alert_id TEXT NOT NULL,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  build_id TEXT NOT NULL,\n  sequence INTEGER NOT NULL CHECK (sequence >= 1),\n  previous_event_id TEXT,\n  kind TEXT NOT NULL CHECK (kind IN ('opened','reopened','acknowledged','resolved','notification-delivered','notification-failed')),\n  status_after TEXT NOT NULL CHECK (status_after IN ('open','acknowledged','resolved')),\n  code TEXT NOT NULL CHECK (code IN ('OPS_BACKUP_FAILED','OPS_PROBE_FAILED','OPS_BACKUP_STALE','OPS_MONITOR_UNKNOWN','OPS_NOTIFICATION_FAILED','OPS_RETENTION_FAILED')),\n  job_id TEXT,\n  actor_user_id TEXT,\n  request_id TEXT NOT NULL,\n  actor_key TEXT NOT NULL,\n  request_digest TEXT NOT NULL CHECK (length(request_digest) = 71 AND substr(request_digest,1,7) = 'sha256:'),\n  receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json)),\n  public_json TEXT NOT NULL CHECK (json_valid(public_json)),\n  created_at INTEGER NOT NULL CHECK (created_at >= 0),\n  UNIQUE (alert_id,sequence),\n  UNIQUE (environment,installation_id,ops_installation_id,actor_key,request_id),\n  UNIQUE (id,alert_id,environment,installation_id,ops_installation_id),\n  CHECK ((sequence = 1 AND previous_event_id IS NULL) OR (sequence > 1 AND previous_event_id IS NOT NULL)),\n  CHECK ((sequence = 1 AND kind = 'opened') OR (sequence > 1 AND kind <> 'opened')),\n  FOREIGN KEY (job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job(id,environment,installation_id,ops_installation_id),\n  FOREIGN KEY (previous_event_id,alert_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_alert_event(id,alert_id,environment,installation_id,ops_installation_id)\n)",
  },
  {
    type: 'trigger',
    name: 'ops_alert_event_chain',
    tbl_name: 'ops_alert_event',
    sql: "CREATE TRIGGER ops_alert_event_chain BEFORE INSERT ON ops_alert_event WHEN NEW.sequence > 1 BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM ops_alert_event WHERE id=NEW.previous_event_id AND alert_id=NEW.alert_id AND code=NEW.code AND sequence=NEW.sequence-1 AND created_at<=NEW.created_at)\n    THEN RAISE(ABORT,'OPS_EVENT_CHAIN') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_alert_event_no_delete',
    tbl_name: 'ops_alert_event',
    sql: "CREATE TRIGGER ops_alert_event_no_delete BEFORE DELETE ON ops_alert_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_alert_event_no_update',
    tbl_name: 'ops_alert_event',
    sql: "CREATE TRIGGER ops_alert_event_no_update BEFORE UPDATE ON ops_alert_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'index',
    name: 'ops_alert_latest',
    tbl_name: 'ops_alert_event',
    sql: 'CREATE INDEX ops_alert_latest ON ops_alert_event(environment,installation_id,ops_installation_id,alert_id,sequence DESC)',
  },
  {
    type: 'table',
    name: 'ops_archive',
    tbl_name: 'ops_archive',
    sql: "CREATE TABLE \"ops_archive\" (\n  id TEXT PRIMARY KEY,\n  job_id TEXT NOT NULL,\n  attempt_id TEXT NOT NULL,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  build_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK (kind IN ('learning','operations')),\n  format TEXT NOT NULL CHECK (format IN ('pilot-admin-backup-4','pilot-admin-backup-5','pilot-ops-backup-1','pilot-ops-backup-2')),\n  object_ref TEXT NOT NULL,\n  key_id TEXT NOT NULL,\n  plaintext_digest TEXT NOT NULL CHECK (length(plaintext_digest) = 71 AND substr(plaintext_digest,1,7) = 'sha256:'),\n  ciphertext_digest TEXT NOT NULL CHECK (length(ciphertext_digest) = 71 AND substr(ciphertext_digest,1,7) = 'sha256:'),\n  byte_size INTEGER NOT NULL CHECK (byte_size > 0),\n  data_at INTEGER NOT NULL CHECK (data_at >= 0),\n  created_at INTEGER NOT NULL CHECK (created_at >= data_at),\n  verified_at INTEGER NOT NULL CHECK (verified_at >= created_at),\n  daily_slot TEXT NOT NULL,\n  weekly_slot TEXT,\n  verification_event_id TEXT NOT NULL,\n  UNIQUE (job_id,attempt_id,kind),\n  UNIQUE (environment,ops_installation_id,object_ref),\n  UNIQUE (id,environment,installation_id,ops_installation_id),\n  CHECK ((kind = 'learning' AND format IN ('pilot-admin-backup-4','pilot-admin-backup-5')) OR (kind = 'operations' AND format IN ('pilot-ops-backup-1','pilot-ops-backup-2'))),\n  FOREIGN KEY (job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job(id,environment,installation_id,ops_installation_id),\n  FOREIGN KEY (verification_event_id,job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job_event(id,job_id,environment,installation_id,ops_installation_id)\n    DEFERRABLE INITIALLY DEFERRED\n)",
  },
  {
    type: 'trigger',
    name: 'ops_archive_no_delete',
    tbl_name: 'ops_archive',
    sql: "CREATE TRIGGER ops_archive_no_delete BEFORE DELETE ON ops_archive BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_archive_no_update',
    tbl_name: 'ops_archive',
    sql: "CREATE TRIGGER ops_archive_no_update BEFORE UPDATE ON ops_archive BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'index',
    name: 'ops_archive_points',
    tbl_name: 'ops_archive',
    sql: 'CREATE INDEX ops_archive_points ON ops_archive(environment,installation_id,ops_installation_id,kind,verified_at,id)',
  },
  {
    type: 'table',
    name: 'ops_feedback',
    tbl_name: 'ops_feedback',
    sql: "CREATE TABLE ops_feedback (\n  id TEXT PRIMARY KEY,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  build_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK (kind IN ('feedback','observation')),\n  submission_build_id TEXT NOT NULL,\n  source_role TEXT NOT NULL CHECK (source_role IN ('parent','operator')),\n  actor_key TEXT NOT NULL,\n  operator_user_id TEXT,\n  request_id TEXT NOT NULL,\n  request_digest TEXT NOT NULL CHECK (length(request_digest) = 71 AND substr(request_digest,1,7) = 'sha256:'),\n  request_json TEXT CHECK (request_json IS NULL OR json_valid(request_json)),\n  receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json)),\n  child_id TEXT,\n  run_id TEXT,\n  run_installation_id TEXT,\n  candidate_id TEXT NOT NULL,\n  lesson_id TEXT NOT NULL,\n  lesson_version TEXT NOT NULL,\n  content_digest TEXT NOT NULL CHECK (length(content_digest) = 71 AND substr(content_digest,1,7) = 'sha256:'),\n  category TEXT CHECK (category IN ('confusion','sound','saving','access','other')),\n  observation_kind TEXT CHECK (observation_kind IN ('actual','synthetic')),\n  observed_at INTEGER CHECK (observed_at IS NULL OR observed_at >= 0),\n  private_json TEXT CHECK (private_json IS NULL OR json_valid(private_json)),\n  created_at INTEGER NOT NULL CHECK (created_at >= 0),\n  expires_at INTEGER NOT NULL CHECK (expires_at = created_at + 2592000000),\n  revision INTEGER NOT NULL CHECK (revision >= 1),\n  severity TEXT NOT NULL CHECK (severity IN ('blocking','high','normal','low')),\n  owner_ref TEXT,\n  status TEXT NOT NULL CHECK (status IN ('open','in-progress','awaiting-review','resolved','expired')),\n  next_review_at INTEGER CHECK (next_review_at IS NULL OR next_review_at >= 0),\n  updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),\n  details_removed_at INTEGER,\n  latest_event_id TEXT NOT NULL,\n  redaction_event_id TEXT,\n  UNIQUE (environment,installation_id,ops_installation_id,actor_key,request_id),\n  UNIQUE (id,environment,installation_id,ops_installation_id),\n  CHECK ((kind = 'feedback' AND source_role = 'parent' AND child_id IS NOT NULL AND run_id IS NOT NULL AND run_installation_id IS NOT NULL AND category IS NOT NULL AND observation_kind IS NULL AND observed_at IS NULL AND operator_user_id IS NULL)\n    OR (kind = 'observation' AND source_role = 'operator' AND child_id IS NULL AND run_id IS NULL AND run_installation_id IS NULL AND category IS NULL AND observation_kind IS NOT NULL AND observed_at IS NOT NULL AND operator_user_id IS NOT NULL)),\n  CHECK ((details_removed_at IS NULL AND status <> 'expired' AND private_json IS NOT NULL AND request_json IS NOT NULL AND redaction_event_id IS NULL)\n    OR (details_removed_at IS NOT NULL AND details_removed_at >= expires_at AND status = 'expired' AND private_json IS NULL AND request_json IS NULL AND owner_ref IS NULL AND next_review_at IS NULL AND redaction_event_id IS NOT NULL AND redaction_event_id = latest_event_id)),\n  FOREIGN KEY (latest_event_id,id,revision,environment,installation_id,ops_installation_id)\n    REFERENCES ops_feedback_event(id,record_id,sequence,environment,installation_id,ops_installation_id)\n    DEFERRABLE INITIALLY DEFERRED\n)",
  },
  {
    type: 'table',
    name: 'ops_feedback_event',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TABLE ops_feedback_event (\n  id TEXT PRIMARY KEY,\n  record_id TEXT NOT NULL,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  sequence INTEGER NOT NULL CHECK (sequence >= 1),\n  previous_event_id TEXT,\n  kind TEXT NOT NULL CHECK (kind IN ('submitted','triaged','corrected','redacted')),\n  actor_user_id TEXT,\n  actor_key TEXT NOT NULL,\n  request_id TEXT NOT NULL,\n  request_digest TEXT NOT NULL CHECK (length(request_digest) = 71 AND substr(request_digest,1,7) = 'sha256:'),\n  request_json TEXT CHECK (request_json IS NULL OR json_valid(request_json)),\n  receipt_json TEXT NOT NULL CHECK (json_valid(receipt_json)),\n  public_json TEXT NOT NULL CHECK (json_valid(public_json)),\n  private_json TEXT CHECK (private_json IS NULL OR json_valid(private_json)),\n  redacted_at INTEGER,\n  created_at INTEGER NOT NULL CHECK (created_at >= 0),\n  UNIQUE (record_id,sequence),\n  UNIQUE (environment,installation_id,ops_installation_id,actor_key,request_id),\n  UNIQUE (id,record_id,sequence,environment,installation_id,ops_installation_id),\n  UNIQUE (id,record_id,environment,installation_id,ops_installation_id),\n  CHECK ((sequence = 1 AND previous_event_id IS NULL AND kind = 'submitted') OR (sequence > 1 AND previous_event_id IS NOT NULL AND kind <> 'submitted')),\n  CHECK ((redacted_at IS NULL AND kind <> 'redacted' AND request_json IS NOT NULL AND private_json IS NOT NULL)\n    OR (redacted_at IS NOT NULL AND request_json IS NULL AND private_json IS NULL)),\n  FOREIGN KEY (record_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_feedback(id,environment,installation_id,ops_installation_id),\n  FOREIGN KEY (previous_event_id,record_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_feedback_event(id,record_id,environment,installation_id,ops_installation_id)\n)",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_event_chain',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_event_chain BEFORE INSERT ON ops_feedback_event WHEN NEW.sequence > 1 BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM ops_feedback_event WHERE id=NEW.previous_event_id AND record_id=NEW.record_id AND sequence=NEW.sequence-1 AND created_at<=NEW.created_at)\n    THEN RAISE(ABORT,'OPS_EVENT_CHAIN') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_event_no_delete',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_event_no_delete BEFORE DELETE ON ops_feedback_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_event_redaction',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_event_redaction BEFORE UPDATE ON ops_feedback_event BEGIN\n  SELECT CASE WHEN NEW.id IS NOT OLD.id OR NEW.record_id IS NOT OLD.record_id OR NEW.environment IS NOT OLD.environment OR NEW.installation_id IS NOT OLD.installation_id OR NEW.ops_installation_id IS NOT OLD.ops_installation_id OR NEW.sequence IS NOT OLD.sequence OR NEW.previous_event_id IS NOT OLD.previous_event_id OR NEW.kind IS NOT OLD.kind OR NEW.actor_user_id IS NOT OLD.actor_user_id OR NEW.actor_key IS NOT OLD.actor_key OR NEW.request_id IS NOT OLD.request_id OR NEW.request_digest IS NOT OLD.request_digest OR NEW.receipt_json IS NOT OLD.receipt_json OR NEW.public_json IS NOT OLD.public_json OR NEW.created_at IS NOT OLD.created_at OR OLD.redacted_at IS NOT NULL OR NEW.request_json IS NOT NULL OR NEW.private_json IS NOT NULL OR NEW.redacted_at IS NULL OR NOT EXISTS (SELECT 1 FROM ops_feedback WHERE id=NEW.record_id AND details_removed_at=NEW.redacted_at AND details_removed_at>=expires_at AND status='expired')\n    THEN RAISE(ABORT,'OPS_REDACTION_INVALID') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_expired_final_event',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_expired_final_event BEFORE INSERT ON ops_feedback_event WHEN NEW.kind<>'redacted' BEGIN\n  SELECT CASE WHEN EXISTS (SELECT 1 FROM ops_feedback WHERE id=NEW.record_id AND status='expired' AND revision=NEW.sequence)\n    THEN RAISE(ABORT,'OPS_REDACTION_INVALID') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_expired_projection',
    tbl_name: 'ops_feedback',
    sql: "CREATE TRIGGER ops_feedback_expired_projection BEFORE UPDATE ON ops_feedback WHEN NEW.status='expired' BEGIN\n  SELECT CASE WHEN EXISTS (SELECT 1 FROM ops_feedback_event WHERE id=NEW.latest_event_id AND kind<>'redacted')\n    THEN RAISE(ABORT,'OPS_REDACTION_INVALID') END;\nEND",
  },
  {
    type: 'index',
    name: 'ops_feedback_expiry',
    tbl_name: 'ops_feedback',
    sql: 'CREATE INDEX ops_feedback_expiry ON ops_feedback(details_removed_at,expires_at,id)',
  },
  {
    type: 'trigger',
    name: 'ops_feedback_identity',
    tbl_name: 'ops_feedback',
    sql: "CREATE TRIGGER ops_feedback_identity BEFORE UPDATE ON ops_feedback WHEN NEW.id IS NOT OLD.id OR NEW.environment IS NOT OLD.environment OR NEW.installation_id IS NOT OLD.installation_id OR NEW.ops_installation_id IS NOT OLD.ops_installation_id OR NEW.build_id IS NOT OLD.build_id OR NEW.kind IS NOT OLD.kind OR NEW.submission_build_id IS NOT OLD.submission_build_id OR NEW.source_role IS NOT OLD.source_role OR NEW.actor_key IS NOT OLD.actor_key OR NEW.operator_user_id IS NOT OLD.operator_user_id OR NEW.request_id IS NOT OLD.request_id OR NEW.request_digest IS NOT OLD.request_digest OR NEW.receipt_json IS NOT OLD.receipt_json OR NEW.child_id IS NOT OLD.child_id OR NEW.run_id IS NOT OLD.run_id OR NEW.run_installation_id IS NOT OLD.run_installation_id OR NEW.candidate_id IS NOT OLD.candidate_id OR NEW.lesson_id IS NOT OLD.lesson_id OR NEW.lesson_version IS NOT OLD.lesson_version OR NEW.content_digest IS NOT OLD.content_digest OR NEW.category IS NOT OLD.category OR NEW.observation_kind IS NOT OLD.observation_kind OR NEW.observed_at IS NOT OLD.observed_at OR NEW.created_at IS NOT OLD.created_at OR NEW.expires_at IS NOT OLD.expires_at OR NEW.revision<>OLD.revision+1 OR OLD.details_removed_at IS NOT NULL OR NEW.updated_at<OLD.updated_at BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_no_delete',
    tbl_name: 'ops_feedback',
    sql: "CREATE TRIGGER ops_feedback_no_delete BEFORE DELETE ON ops_feedback BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_feedback_private_update',
    tbl_name: 'ops_feedback',
    sql: "CREATE TRIGGER ops_feedback_private_update BEFORE UPDATE ON ops_feedback WHEN (NEW.request_json IS NOT OLD.request_json OR NEW.private_json IS NOT OLD.private_json) AND NOT (NEW.request_json IS NULL AND NEW.private_json IS NULL AND OLD.details_removed_at IS NULL AND NEW.details_removed_at>=OLD.expires_at AND NEW.status='expired') BEGIN SELECT RAISE(ABORT,'OPS_REDACTION_INVALID'); END",
  },
  {
    type: 'index',
    name: 'ops_feedback_queue',
    tbl_name: 'ops_feedback',
    sql: 'CREATE INDEX ops_feedback_queue ON ops_feedback(environment,installation_id,ops_installation_id,status,kind,created_at,id)',
  },
  {
    type: 'trigger',
    name: 'ops_feedback_queue_insert',
    tbl_name: 'ops_feedback',
    sql: 'CREATE TRIGGER ops_feedback_queue_insert AFTER INSERT ON ops_feedback BEGIN\n  UPDATE ops_installation SET queue_revision=queue_revision+1 WHERE id=1;\nEND',
  },
  {
    type: 'trigger',
    name: 'ops_feedback_queue_update',
    tbl_name: 'ops_feedback',
    sql: 'CREATE TRIGGER ops_feedback_queue_update AFTER UPDATE ON ops_feedback BEGIN\n  UPDATE ops_installation SET queue_revision=queue_revision+1 WHERE id=1;\nEND',
  },
  {
    type: 'trigger',
    name: 'ops_feedback_redaction_insert',
    tbl_name: 'ops_feedback_event',
    sql: "CREATE TRIGGER ops_feedback_redaction_insert BEFORE INSERT ON ops_feedback_event WHEN NEW.kind='redacted' BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM ops_feedback WHERE id=NEW.record_id AND status='expired' AND details_removed_at=NEW.redacted_at AND latest_event_id=NEW.id AND expires_at<=NEW.created_at)\n    THEN RAISE(ABORT,'OPS_REDACTION_INVALID') END;\nEND",
  },
  {
    type: 'table',
    name: 'ops_installation',
    tbl_name: 'ops_installation',
    sql: 'CREATE TABLE "ops_installation" (\n  id INTEGER PRIMARY KEY CHECK (id = 1),\n  installation_id TEXT NOT NULL UNIQUE,\n  environment TEXT NOT NULL,\n  learning_installation_id TEXT NOT NULL,\n  schema_version TEXT NOT NULL CHECK (schema_version = \'pilot-ops-schema-2\'),\n  queue_revision INTEGER NOT NULL DEFAULT 0 CHECK (queue_revision >= 0),\n  created_at INTEGER NOT NULL CHECK (created_at >= 0)\n)',
  },
  {
    type: 'trigger',
    name: 'ops_installation_identity',
    tbl_name: 'ops_installation',
    sql: "CREATE TRIGGER ops_installation_identity BEFORE UPDATE ON ops_installation WHEN NEW.installation_id IS NOT OLD.installation_id OR NEW.environment IS NOT OLD.environment OR NEW.learning_installation_id IS NOT OLD.learning_installation_id OR NEW.schema_version IS NOT OLD.schema_version OR NEW.created_at IS NOT OLD.created_at OR NEW.queue_revision<OLD.queue_revision BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_installation_no_delete',
    tbl_name: 'ops_installation',
    sql: "CREATE TRIGGER ops_installation_no_delete BEFORE DELETE ON ops_installation BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'table',
    name: 'ops_job',
    tbl_name: 'ops_job',
    sql: "CREATE TABLE ops_job (\n  id TEXT PRIMARY KEY,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  build_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK (kind IN ('backup','monitor','retention','reconcile')),\n  utc_slot TEXT NOT NULL,\n  objects_json TEXT NOT NULL CHECK (json_valid(objects_json)),\n  revision INTEGER NOT NULL CHECK (revision >= 1),\n  status TEXT NOT NULL CHECK (status IN ('running','uncertain','succeeded','failed')),\n  attempt_id TEXT NOT NULL,\n  attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),\n  lease_until INTEGER,\n  started_at INTEGER NOT NULL CHECK (started_at >= 0),\n  ended_at INTEGER,\n  error_code TEXT,\n  latest_event_id TEXT NOT NULL,\n  UNIQUE (environment,installation_id,ops_installation_id,kind,utc_slot),\n  UNIQUE (id,environment,installation_id,ops_installation_id),\n  CHECK (lease_until IS NULL OR lease_until >= started_at),\n  CHECK (ended_at IS NULL OR ended_at >= started_at),\n  CHECK ((status = 'running' AND lease_until IS NOT NULL AND ended_at IS NULL)\n    OR (status = 'uncertain' AND lease_until IS NULL AND ended_at IS NULL)\n    OR (status IN ('succeeded','failed') AND lease_until IS NULL AND ended_at IS NOT NULL)),\n  FOREIGN KEY (latest_event_id,id,revision,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job_event(id,job_id,sequence,environment,installation_id,ops_installation_id)\n    DEFERRABLE INITIALLY DEFERRED\n)",
  },
  {
    type: 'index',
    name: 'ops_job_current',
    tbl_name: 'ops_job',
    sql: 'CREATE INDEX ops_job_current ON ops_job(environment,installation_id,ops_installation_id,status,started_at,id)',
  },
  {
    type: 'table',
    name: 'ops_job_event',
    tbl_name: 'ops_job_event',
    sql: "CREATE TABLE ops_job_event (\n  id TEXT PRIMARY KEY,\n  job_id TEXT NOT NULL,\n  environment TEXT NOT NULL,\n  installation_id TEXT NOT NULL,\n  ops_installation_id TEXT NOT NULL,\n  sequence INTEGER NOT NULL CHECK (sequence >= 1),\n  previous_event_id TEXT,\n  attempt_id TEXT NOT NULL,\n  kind TEXT NOT NULL CHECK (kind IN ('acquired','uncertain','archive-verified','completed','failed','reconciled','archive-deleted')),\n  status_after TEXT NOT NULL CHECK (status_after IN ('running','uncertain','succeeded','failed')),\n  request_digest TEXT NOT NULL CHECK (length(request_digest) = 71 AND substr(request_digest,1,7) = 'sha256:'),\n  public_json TEXT NOT NULL CHECK (json_valid(public_json)),\n  created_at INTEGER NOT NULL CHECK (created_at >= 0),\n  UNIQUE (job_id,sequence),\n  UNIQUE (id,job_id,sequence,environment,installation_id,ops_installation_id),\n  UNIQUE (id,job_id,environment,installation_id,ops_installation_id),\n  CHECK ((sequence = 1 AND previous_event_id IS NULL) OR (sequence > 1 AND previous_event_id IS NOT NULL)),\n  FOREIGN KEY (job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job(id,environment,installation_id,ops_installation_id),\n  FOREIGN KEY (previous_event_id,job_id,environment,installation_id,ops_installation_id)\n    REFERENCES ops_job_event(id,job_id,environment,installation_id,ops_installation_id)\n)",
  },
  {
    type: 'trigger',
    name: 'ops_job_event_chain',
    tbl_name: 'ops_job_event',
    sql: "CREATE TRIGGER ops_job_event_chain BEFORE INSERT ON ops_job_event WHEN NEW.sequence > 1 BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM ops_job_event WHERE id=NEW.previous_event_id AND job_id=NEW.job_id AND sequence=NEW.sequence-1 AND created_at<=NEW.created_at)\n    THEN RAISE(ABORT,'OPS_EVENT_CHAIN') END;\nEND",
  },
  {
    type: 'trigger',
    name: 'ops_job_event_no_delete',
    tbl_name: 'ops_job_event',
    sql: "CREATE TRIGGER ops_job_event_no_delete BEFORE DELETE ON ops_job_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_job_event_no_update',
    tbl_name: 'ops_job_event',
    sql: "CREATE TRIGGER ops_job_event_no_update BEFORE UPDATE ON ops_job_event BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_job_identity',
    tbl_name: 'ops_job',
    sql: "CREATE TRIGGER ops_job_identity BEFORE UPDATE ON ops_job WHEN NEW.id IS NOT OLD.id OR NEW.environment IS NOT OLD.environment OR NEW.installation_id IS NOT OLD.installation_id OR NEW.ops_installation_id IS NOT OLD.ops_installation_id OR NEW.build_id IS NOT OLD.build_id OR NEW.kind IS NOT OLD.kind OR NEW.utc_slot IS NOT OLD.utc_slot OR NEW.objects_json IS NOT OLD.objects_json OR NEW.revision<>OLD.revision+1 BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_job_no_delete',
    tbl_name: 'ops_job',
    sql: "CREATE TRIGGER ops_job_no_delete BEFORE DELETE ON ops_job BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'table',
    name: 'ops_schema_history',
    tbl_name: 'ops_schema_history',
    sql: "CREATE TABLE \"ops_schema_history\" (\n  version INTEGER PRIMARY KEY CHECK (version IN (0,1)),\n  name TEXT NOT NULL CHECK ((version=0 AND name='0000_ops.sql') OR (version=1 AND name='0001_collection_archives.sql')),\n  checksum TEXT NOT NULL CHECK (length(checksum) = 64),\n  applied_at INTEGER NOT NULL CHECK (applied_at >= 0)\n)",
  },
  {
    type: 'trigger',
    name: 'ops_schema_history_no_delete',
    tbl_name: 'ops_schema_history',
    sql: "CREATE TRIGGER ops_schema_history_no_delete BEFORE DELETE ON ops_schema_history BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
  {
    type: 'trigger',
    name: 'ops_schema_history_no_update',
    tbl_name: 'ops_schema_history',
    sql: "CREATE TRIGGER ops_schema_history_no_update BEFORE UPDATE ON ops_schema_history BEGIN SELECT RAISE(ABORT,'OPS_IMMUTABLE'); END",
  },
] as const;
export const OPS_MIGRATIONS_V1 = [
  { name: '0000_ops.sql', version: 0, sha256: OPS_MIGRATION_SHA },
] as const;
export const OPS_MIGRATIONS_V2 = [
  ...OPS_MIGRATIONS_V1,
  {
    name: '0001_collection_archives.sql',
    version: 1,
    sha256: OPS_MIGRATION_V2_SHA,
  },
] as const;

/** Exact reviewed third prefix; server constants contain no Node/script imports. */
export const OPS_MIGRATION_V3_SHA =
  '524eaf2c844099b1eb76de1434ded5b05cefac0eb214f5dbda4b36df4da6ec20';
export const OPS_MIGRATIONS_V3 = [
  ...OPS_MIGRATIONS_V2,
  {
    name: '0002_corpus_archives.sql',
    version: 2,
    sha256: OPS_MIGRATION_V3_SHA,
  },
] as const;
export const OPS_SCHEMA_V3 = OPS_SCHEMA_V2.map((row) => ({
  ...row,
  sql:
    row.name === 'ops_archive'
      ? row.sql
          .replaceAll(
            "'pilot-admin-backup-5'",
            "'pilot-admin-backup-5','pilot-admin-backup-6'",
          )
          .replaceAll(
            "'pilot-ops-backup-2'",
            "'pilot-ops-backup-2','pilot-ops-backup-3'",
          )
      : row.name === 'ops_installation'
        ? row.sql.replaceAll('pilot-ops-schema-2', 'pilot-ops-schema-3')
        : row.name === 'ops_schema_history'
          ? row.sql
              .replace('version IN (0,1)', 'version IN (0,1,2)')
              .replace(
                "(version=1 AND name='0001_collection_archives.sql')",
                "(version=1 AND name='0001_collection_archives.sql') OR (version=2 AND name='0002_corpus_archives.sql')",
              )
          : row.sql,
}));
